# Generated by Django 5.2 on 2025-05-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Инфо'), ('guest', 'Гость'), ('task', 'Задача'), ('warning', 'Внимание')], default='info', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pinned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заметка смены',
                'verbose_name_plural': 'Заметки смены',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
    ]
