# Generated by Django 5.2 on 2025-05-10 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название шаблона чек-листа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон чек-листа',
                'verbose_name_plural': 'Шаблоны чек-листов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unassigned', 'Не назначен'), ('assigned', 'Назначен'), ('in_progress', 'В процессе уборки'), ('completed', 'Уборка завершена'), ('waiting_check', 'Ожидает проверки'), ('checked', 'Проверено'), ('canceled', 'Отменена')], default='unassigned', max_length=20, verbose_name='Статус уборки')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Дата планирования уборки')),
                ('due_time', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Время назначения')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала уборки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения уборки')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Время проверки')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Задача по уборке',
                'verbose_name_plural': 'Задачи по уборке',
                'ordering': ['due_time'],
            },
        ),
        migrations.CreateModel(
            name='CleaningType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название типа уборки')),
            ],
            options={
                'verbose_name': 'Тип уборки',
                'verbose_name_plural': 'Типы уборок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст пункта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения пункта в списке')),
                ('checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cleaning.checklisttemplate', verbose_name='Шаблон чек-листа')),
            ],
            options={
                'verbose_name': 'Пункт шаблона чек-листа',
                'verbose_name_plural': 'Пункты шаблона чек-листа',
                'ordering': ['order'],
            },
        ),
    ]
