# Generated by Django 5.2 on 2025-05-10 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_initial'),
        ('cleaning', '0001_initial'),
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Назначил задачу'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Назначена горничная'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='booking.booking', verbose_name='Связанное бронирование'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_cleaning_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='hotel.room', verbose_name='Номер комнаты для уборки'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='hotel.zone', verbose_name='Зона для уборки'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='cleaning_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='cleaning.cleaningtype', verbose_name='Тип уборки'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='cleaning_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaning.cleaningtype', verbose_name='Тип уборки'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistitemtemplate',
            unique_together={('checklist_template', 'order')},
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['status'], name='cleaning_cl_status_139d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['assigned_to'], name='cleaning_cl_assigne_4479cc_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['due_time'], name='cleaning_cl_due_tim_0ab467_idx'),
        ),
    ]
