# Generated by Django 5.2 on 2025-05-01 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_initial'),
        ('cleaning', '0002_initial'),
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningcheck',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningcheck',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.cleaningchecklisttemplate'),
        ),
        migrations.AddField(
            model_name='cleaningcheckitem',
            name='cleaning_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cleaning.cleaningcheck'),
        ),
        migrations.AddField(
            model_name='cleaningcheckitem',
            name='template_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cleaning.checklistitemtemplate'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='checklist_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.cleaningchecklisttemplate'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
        migrations.AddField(
            model_name='cleaningcheck',
            name='cleaning_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaning.cleaningtask'),
        ),
    ]
