# Generated by Django 5.2 on 2025-05-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
