# Generated by Django 5.2 on 2025-05-23 02:25

from django.db import migrations

def create_cleaning_types(apps, schema_editor):
    CleaningType = apps.get_model("cleaning", "CleaningType")
    CleaningType.objects.get_or_create(name="Текущая уборка")
    CleaningType.objects.get_or_create(name="Уборка после выезда")


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0003_cleaningtype_description'),
    ]

    operations = [
         migrations.RunPython(create_cleaning_types),
    ]
