# Generated by Django 5.2 on 2025-05-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0004_add_default_cleaning_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplate',
            name='cleaning_type',
            field=models.CharField(choices=[('stayover', 'Ежедневная уборка'), ('departure_cleaning', 'Уборка при выезде'), ('deep_cleaning', 'Генеральная уборка'), ('on_demand', 'Уборка по запросу'), ('post_renovation_cleaning', 'Уборка после ремонта'), ('public_area_cleaning', 'Текущая уборка общих зон')], default='stayover', max_length=40, verbose_name='Тип уборки'),
        ),
        migrations.AlterField(
            model_name='cleaningtask',
            name='cleaning_type',
            field=models.CharField(choices=[('stayover', 'Ежедневная уборка'), ('departure_cleaning', 'Уборка при выезде'), ('deep_cleaning', 'Генеральная уборка'), ('on_demand', 'Уборка по запросу'), ('post_renovation_cleaning', 'Уборка после ремонта'), ('public_area_cleaning', 'Текущая уборка общих зон')], default='stayover', max_length=40, verbose_name='Тип уборки'),
        ),
        migrations.DeleteModel(
            name='CleaningType',
        ),
    ]
