# Generated by Django 5.2 on 2025-06-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0006_checklisttemplate_offset_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='is_rush',
            field=models.BooleanField(default=False),
        ),
    ]
