# Generated by Django 5.2 on 2025-06-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0007_cleaningtask_is_rush'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtask',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Не назначен'), ('assigned', 'Назначен'), ('in_progress', 'В процессе уборки'), ('completed', 'Уборка завершена'), ('waiting_check', 'Ожидает проверки'), ('checked', 'Проверено'), ('canceled', 'Отменена'), ('pre_arrival', 'Подготовка к заезду')], default='unassigned', max_length=20, verbose_name='Статус уборки'),
        ),
    ]
