# Generated by Django 5.2 on 2025-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0008_alter_cleaningtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplate',
            name='cleaning_type',
            field=models.CharField(choices=[('stayover', 'Ежедневная уборка'), ('departure_cleaning', 'Уборка при выезде'), ('deep_cleaning', 'Генеральная уборка'), ('on_demand', 'Уборка по запросу'), ('post_renovation_cleaning', 'Уборка после ремонта'), ('public_area_cleaning', 'Текущая уборка общих зон'), ('pre_arrival', 'Подготовка к заезду')], default='stayover', max_length=40, verbose_name='Тип уборки'),
        ),
        migrations.AlterField(
            model_name='cleaningtask',
            name='cleaning_type',
            field=models.CharField(choices=[('stayover', 'Ежедневная уборка'), ('departure_cleaning', 'Уборка при выезде'), ('deep_cleaning', 'Генеральная уборка'), ('on_demand', 'Уборка по запросу'), ('post_renovation_cleaning', 'Уборка после ремонта'), ('public_area_cleaning', 'Текущая уборка общих зон'), ('pre_arrival', 'Подготовка к заезду')], default='stayover', max_length=40, verbose_name='Тип уборки'),
        ),
    ]
