# Generated by Django 5.2 on 2025-06-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0009_alter_checklisttemplate_cleaning_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtask',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Не назначен'), ('assigned', 'Назначен'), ('in_progress', 'В процессе уборки'), ('completed', 'Уборка завершена'), ('waiting_check', 'Ожидает проверки'), ('checking', 'Проверяется'), ('checked', 'Проверено'), ('canceled', 'Отменена')], default='unassigned', max_length=20, verbose_name='Статус уборки'),
        ),
    ]
