# Generated by Django 5.2 on 2025-06-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0010_alter_cleaningtask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaningtask',
            options={'ordering': ['scheduled_date', 'due_time', 'room__number', 'zone__name'], 'verbose_name': 'Задача по уборке', 'verbose_name_plural': 'Задачи по уборке'},
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='associated_checklists',
            field=models.ManyToManyField(blank=True, related_name='cleaning_tasks', to='cleaning.checklisttemplate', verbose_name='Связанные чек-листы'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='checklist_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Данные чек-листа'),
        ),
    ]
