# Generated by Django 5.2 on 2025-05-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='Дата и время заезда')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выезда')),
                ('guest_count', models.PositiveIntegerField(default=2, verbose_name='Количество гостей')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['check_in'],
            },
        ),
    ]
