# Generated by Django 5.2 on 2025-05-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Ожидается'), ('in_progress', 'В процессе проживания'), ('checked_out', 'Выезд выполнен'), ('cancelled', 'Отменено'), ('no_show', 'Не заехал')], default='upcoming', max_length=20),
        ),
    ]
