# Generated by Django 5.2 on 2025-05-10 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название типа номера')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название зоны')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Зона для уборки',
                'verbose_name_plural': 'Зоны для уборки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер комнаты')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят'), ('waiting_checkout', 'Ожидается выезд'), ('dirty', 'Грязный'), ('assigned', 'Назначен'), ('in_progress', 'В процессе уборки'), ('waiting_inspection', 'Ожидает проверки'), ('clean', 'Чистый (готов к заезду)'), ('on_maintenance', 'На обслуживании')], default='free', max_length=20, verbose_name='Статус номера')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.roomtype', verbose_name='Категория номера')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['number'],
                'indexes': [models.Index(fields=['status'], name='hotel_room_status_b531da_idx'), models.Index(fields=['room_type'], name='hotel_room_room_ty_7a9c6c_idx'), models.Index(fields=['is_active'], name='hotel_room_is_acti_283a8c_idx')],
            },
        ),
    ]
