# Generated by Django 5.2 on 2025-05-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят'), ('dirty', 'Грязный'), ('assigned', 'Назначен'), ('in_progress', 'В процессе уборки'), ('waiting_inspection', 'Ожидает проверки'), ('clean', 'Чистый (готов к заезду)'), ('on_maintenance', 'На обслуживании')], default='free', max_length=20, verbose_name='Статус номера'),
        ),
    ]
