# Generated by Django 5.2 on 2025-05-01 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningchecklisttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.roomtype'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='hotel_room_status_b531da_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='hotel_room_room_ty_7a9c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active'], name='hotel_room_is_acti_283a8c_idx'),
        ),
    ]
