# Generated by Django 5.2 on 2025-05-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='status',
            field=models.CharField(choices=[('dirty', 'Грязный'), ('assigned', 'Назначен'), ('in_progress', 'В процессе уборки'), ('clean', 'Чистый')], default='clean', max_length=20, verbose_name='Статус номера'),
        ),
    ]
