# Generated by Django 5.2 on 2025-06-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_zone_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='default_prepared_guests',
            field=models.PositiveIntegerField(default=2, verbose_name='Стандартное кол-во гостей для подготовки'),
        ),
    ]
