# Generated by Django 5.2 on 2025-05-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('housekeeper', 'Горничная'), ('admin', 'Администратор'), ('manager', 'Управляющий'), ('front_desk', 'Ресепшн')], max_length=20, verbose_name='Роль'),
        ),
    ]
