# Generated by Django 5.2 on 2025-05-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('housekeeper', 'Горничная'), ('manager', 'Управляющий'), ('front-desk', 'Ресепшн')], max_length=20, verbose_name='Роль'),
        ),
    ]
