# Generated by Django 5.2 on 2025-06-10 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pushtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushtoken',
            options={'verbose_name': 'Push-токен', 'verbose_name_plural': 'Push-токены'},
        ),
        migrations.AddField(
            model_name='pushtoken',
            name='last_registered_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя регистрация'),
        ),
        migrations.AddField(
            model_name='pushtoken',
            name='platform',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='token',
            field=models.CharField(max_length=255, unique=True, verbose_name='Push-токен'),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
